"""Ground-truth WeeklySpendPoint histories and TrendPrediction outputs,
generated by actually running dajim-web/lib/predictTrend.ts +
dajim-web/lib/historicalSpend.ts (via `npx tsx`) on 2026-08-19 — not
hand-derived. Used to verify prediction.trend_model is a faithful port.

Regenerate by temporarily adding this script to dajim-web/ and running
`npx --yes tsx _gen_expected.ts`, then deleting it:

    import { predictCategoryTrend } from "./lib/predictTrend";
    import { getWeeklySpendHistory } from "./lib/historicalSpend";
    import type { CategoryId } from "./lib/types";

    const categories: CategoryId[] = ["delivery", "cafe", "shopping", "subscription"];
    const out: Record<string, unknown> = {};
    for (const c of categories) {
      const history = getWeeklySpendHistory(c);
      out[c] = { history, prediction: predictCategoryTrend(history) };
    }
    console.log(JSON.stringify(out, null, 2));
"""
from __future__ import annotations

CASES = {
    "delivery": {
        "history": [
            {"week_start": "2026-06-08", "total_won": 118000, "days_elapsed": 7},
            {"week_start": "2026-06-15", "total_won": 124000, "days_elapsed": 7},
            {"week_start": "2026-06-22", "total_won": 129000, "days_elapsed": 7},
            {"week_start": "2026-06-29", "total_won": 137000, "days_elapsed": 7},
            {"week_start": "2026-07-06", "total_won": 142000, "days_elapsed": 7},
            {"week_start": "2026-07-13", "total_won": 150000, "days_elapsed": 7},
            {"week_start": "2026-07-20", "total_won": 158000, "days_elapsed": 7},
            {"week_start": "2026-07-27", "total_won": 167000, "days_elapsed": 7},
            {"week_start": "2026-08-03", "total_won": 98000, "days_elapsed": 4},
        ],
        "prediction": {
            "trend": [129000, 137000, 142000, 150000, 158000, 167000, 171607],
            "projected_month_won": 710883,
            "last_month_won": 617000,
            "change_pct": 15,
        },
    },
    "cafe": {
        "history": [
            {"week_start": "2026-06-08", "total_won": 17500, "days_elapsed": 7},
            {"week_start": "2026-06-15", "total_won": 18200, "days_elapsed": 7},
            {"week_start": "2026-06-22", "total_won": 17800, "days_elapsed": 7},
            {"week_start": "2026-06-29", "total_won": 19000, "days_elapsed": 7},
            {"week_start": "2026-07-06", "total_won": 18700, "days_elapsed": 7},
            {"week_start": "2026-07-13", "total_won": 19600, "days_elapsed": 7},
            {"week_start": "2026-07-20", "total_won": 20100, "days_elapsed": 7},
            {"week_start": "2026-07-27", "total_won": 20800, "days_elapsed": 7},
            {"week_start": "2026-08-03", "total_won": 12400, "days_elapsed": 4},
        ],
        "prediction": {
            "trend": [17800, 19000, 18700, 19600, 20100, 20800, 21392],
            "projected_month_won": 88801,
            "last_month_won": 79200,
            "change_pct": 12,
        },
    },
    "shopping": {
        "history": [
            {"week_start": "2026-06-08", "total_won": 58000, "days_elapsed": 7},
            {"week_start": "2026-06-15", "total_won": 55000, "days_elapsed": 7},
            {"week_start": "2026-06-22", "total_won": 56500, "days_elapsed": 7},
            {"week_start": "2026-06-29", "total_won": 52000, "days_elapsed": 7},
            {"week_start": "2026-07-06", "total_won": 50000, "days_elapsed": 7},
            {"week_start": "2026-07-13", "total_won": 48500, "days_elapsed": 7},
            {"week_start": "2026-07-20", "total_won": 46000, "days_elapsed": 7},
            {"week_start": "2026-07-27", "total_won": 44500, "days_elapsed": 7},
            {"week_start": "2026-08-03", "total_won": 24000, "days_elapsed": 4},
        ],
        "prediction": {
            "trend": [56500, 52000, 50000, 48500, 46000, 44500, 42191],
            "projected_month_won": 174683,
            "last_month_won": 189000,
            "change_pct": -8,
        },
    },
    "subscription": {
        "history": [
            {"week_start": "2026-06-08", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-06-15", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-06-22", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-06-29", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-07-06", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-07-13", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-07-20", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-07-27", "total_won": 10475, "days_elapsed": 7},
            {"week_start": "2026-08-03", "total_won": 5985, "days_elapsed": 4},
        ],
        "prediction": {
            "trend": [10475, 10475, 10475, 10475, 10475, 10475, 10474],
            "projected_month_won": 43393,
            "last_month_won": 41900,
            "change_pct": 4,
        },
    },
}
